FROM bitnami/spark:latest

USER root

RUN apt-get update && \
    apt-get install -y iputils-ping python3 python3-distutils curl && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3 && \
    pip3 install pyspark==3.5.4 py4j==0.10.9.7 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER 1001
